### ISSUE TITLE
spacing of content thumbnails and labels is way too big when viewed on mobile

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#412]
Make it all fit.

**Comment by reynoldsnlp** [comment]
In general, anything related to the main page and the player should be mobile-friendly. Do lots of things on those pages to make sure that it is operating well.

**Comment by dallan21** [comment]
-When you click on the content in order to edit it, the save button is not in a fixed position. It moves when you scroll down the editor on the phone
-The "create new content" box is huge compared to the other content thumbnails
- the name, published, and language/closed caption stuff is moved over on top of the thumbnail
- the video, subtitle, clip editors are a bit too big

**Comment by dallan21** [comment]
![IMG_0710](https://user-images.githubusercontent.com/90338790/167936204-11a819d8-2de8-4349-8eee-2bded96fe5e9.jpeg)
