### ISSUE TITLE
Global Text Size

### ISSUE THREAD

**Issue by Aaron-M-Anderson** [BYU-ODH/yvideo-client#475]
The Global text-size is too small overall in the opinion of a few of us, and changing the size to like 12px instead of 10 doesn't seem to cause any glaring issues. I'm a proponent of changing the font-size to 12px at least, which is bound to cause issues that I haven't noticed in preliminary testing. So the job is to change the font-size in :root to 12px, and then to systematically look around the entire site to observe what has changed, and what doesn't look or feel right anymore, and then make the necessary changes.

**Comment by dallan21** [comment]
Things to fix with changing the font size to `12`:

1. Mobile S (320px) is off and would need to be fixed
2. Some of the tooltips will n
<img width="1293" alt="Screen Shot 2022-06-06 at 5 34 38 PM" src="https://user-images.githubusercontent.com/90338790/172266114-b5268459-bb0b-4a67-9940-0d34996aa3bc.png">
eed to be resized because the text is too big for it
3. On the manage collections page, the page is now too big and will need to be resized because you have to scroll left or right on a standard laptop screen. 
4. under the `Edit User Access` page the username label is not higher than the rest and the arrows are under the label instead of right next to it. 
5. On `Admin Dashboard` the `last login` label now has the arrows under instead of off to the right 
6. The top part of the video, clip editor, and subtitle editor (video container, and side menu editor) are cut off. 
7. the `Add Subtitle Track` button is now out of place. 
8. you now have to scroll on the timeline bar in video and subtitle editor 
9. on the subtitles cards in `subtitle editor` the icons are not centered anymore and they are almost being pushed out of the box. 
10. We may need to update the manage collections help modal

I will add more as I keep looking through the website.
