### ISSUE TITLE
Creating clips in the clips editor is clunky :-(

### ISSUE THREAD

**Issue by reynoldsnlp** [BYU-ODH/yvideo-client#624]

**Comment by dallan21** [comment]
Things to change: (will add more as I  play around with the clip editor)
1. Possibly add in a `use current time` option for the editors
2. add in a `are you sure you want to delete` modal
3. when you click on the plus icon, have something either pop up to enter the name of the clip or auto focus on the name box. Because right now you can create a clip and just leave the name blank
