### ISSUE TITLE
Validate teaching units under "Edit User Access"

### ISSUE THREAD

**Issue by ThCovenant** [BYU-ODH/yvideo-client#633]

**Comment by reynoldsnlp** [comment]
Currently, teachers are allowed to type whatever they want for teaching units and course numbers. For example, one professor was using `SPANISH`/`PORTUGUESE` instead of `SPAN`/`PORT`. Similarly, a course was listed as `601 B` (note the space) instead of `601B`.

The courses added under "Edit User Access", should be validated whether the Dept is one of the following teaching units. If it is not, then add a yellow exclamation mark badge to the department and enable a tooltip on hover that says: `This Department is not in our list of teaching units. Check for the exact spelling in the course catalog.`

`['A HTG', 'ACC', 'AEROS', 'AFRIK', 'AM ST', 'ANES', 'ANTHR', 'ARAB', 'ARMEN', 'ART', 'ARTED', 'ARTHC', 'ASIAN', 'ASL', 'BIO', 'BULGN', 'C S', 'CANT', 'CCE', 'CE', 'CEBU', 'CELL', 'CFM', 'CH EN', 'CHEM', 'CHIN', 'CL CV', 'CLSCS', 'CMLIT', 'CMPST', 'COMD', 'COMMS', 'CPSE', 'CREOL', 'CROAT', 'CSANM', 'DANCE', 'DANSH', 'DES', 'DESAN', 'DESGD', 'DESIL', 'DESPH', 'DIGHT', 'DUTCH', 'EC EN', 'ECE', 'ECON', 'EDLF', 'EIME', 'EL ED', 'ELING', 'EMBA', 'ENG T', 'ENGL', 'ENT', 'ESL', 'ESTON', 'EUROP', 'EXDM', 'EXSC', 'FHSS', 'FIJI', 'FIN', 'FINN', 'FLANG', 'FNART', 'FREN', 'GEOG', 'GEOL', 'GERM', 'GREEK', 'GSCM', 'GWS', 'HAWAI', 'HCOLL', 'HEB', 'HILIG', 'HINDI', 'HIST', 'HLTH', 'HMONG', 'HONRS', 'HRM', 'IAS', 'ICLND', 'ICS', 'IHUM', 'INDES', 'INDON', 'IP&T', 'IS', 'IT&C', 'ITAL', 'JAPAN', 'KHMER', 'KICHE', 'KOREA', 'LATIN', 'LATVI', 'LAW', 'LFSCI', 'LING', 'LITHU', 'LT AM', 'M COM', 'MALAG', 'MARSH', 'MATH', 'MBA', 'MDT', 'ME EN', 'MESA', 'MFGEN', 'MFHD', 'MFT', 'MIL S', 'MKTG', 'MMBIO', 'MPA', 'MSB', 'MTHED', 'MUSIC', 'NAVAJ', 'NDFS', 'NE LG', 'NES', 'NEURO', 'NORWE', 'NURS', 'PERSI', 'PETE', 'PHIL', 'PHSCS', 'PHY S', 'PLANG', 'POLI', 'POLSH', 'PORT', 'PSYCH', 'PWS', 'QUECH', 'REL A', 'REL C', 'REL E', 'ROM', 'RUSS', 'SAMOA', 'SC ED', 'SCAND', 'SFL', 'SLAT', 'SLN', 'SLOVK', 'SOC', 'SOC W', 'SPAN', 'SRBIA', 'STAC', 'STAT', 'STDEV', 'STRAT', 'SWAHI', 'SWED', 'SWELL', 'T ED', 'TAGAL', 'TECH', 'TEE', 'TELL', 'TES', 'TEST', 'THAI', 'TMA', 'TONGA', 'TURK', 'UKRAI', 'UNIV', 'VIET', 'WELSH', 'WRTG']`

Similarly, if the course number does not match the regular expression `/[0-9]+[A-Z]?/`, then add a yellow exclamation point badge to the course number, and enable a tooltip that says `This course number may not be spelled correctly. Check for the exact spelling in the course catalog.`

Finally, change the label `Courses` to `Courses (deleted after every semester/term)`, or suggest something else to Rob to get this idea across.

**Comment by reynoldsnlp** [comment]
The list of teaching units should probably go in a config file.

**Comment by reynoldsnlp** [comment]
One other thing is to remove any surrounding whitespace (using `trim()`) before saving any of these fields. Just had a course fail because the teacher had put a space after the Dept.
